# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: WDIDT
run-name: WDIDT-${{github.run_id}}.${{github.run_number}}.${{github.run_attempt}}
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]

    - name: Lint with black
      run: |
        python -m black --check .
    - name: Analyze with mypy
      run: |
        python -m mypy wdidt
    - name: Test with pytest
      run: |
        python -m pytest
      continue-on-error: true
